[package]
name = "kpass"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clipboard-ext = { version = "0.2.0", default-features = false, features = ["x11-bin"] }
cocoon = "0.4.1"
inquire = "0.7.1"
keepass = "0.7.7"
wl-clipboard-rs = "0.8.1"
